// <auto-generated />
using System;
using Dwapi.Vmmc.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dwapi.Vmmc.Infrastructure.Migrations
{
    [DbContext(typeof(VmmcContext))]
    [Migration("20250512064735_InitialVMMCMigrations")]
    partial class InitialVMMCMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Cargoes");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.Docket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Dockets");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MasterFacilityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SnapshotSiteCode")
                        .HasColumnType("int");

                    b.Property<int?>("SnapshotVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterFacilityId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateArrived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmrSetup")
                        .HasColumnType("int");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Recieved")
                        .HasColumnType("int");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sent")
                        .HasColumnType("int");

                    b.Property<Guid?>("Session")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.MasterFacility", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SnapshotSiteCode")
                        .HasColumnType("int");

                    b.Property<int?>("SnapshotVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MasterFacilities");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocketId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcDiscontinuationExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiscontinuationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VMMCId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("VmmcDiscontinuationExtracts");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcEnrollmentExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountyOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EncounterDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SourceVMMCInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VMMCId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("VmmcEnrollmentExtracts");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcFollowupVisitExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AEDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AEManagement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AESeverity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AEType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventPostCircumcision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CadreClinician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DaySinceLastCircumsicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EncounterDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VMMCId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("VmmcFollowupVisitExtracts");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcMhpeExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adherance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Anaemia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BleedingDisorder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD4Count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientEverHadSurgery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTetanusBoosterGiven")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diabetes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyRetractingForeskin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyReturninForeskinNormal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EncounterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Epispadia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityReceivingCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenitalSore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVAIDS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVStatusSelfReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hypospadia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastVL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PainUrination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PulseRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reasonresultsunknown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferredServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexualFunctionConcerns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SpecifySurgery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartARTDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SugarLevels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwellingScrotum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TetanusBoosterGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrethralDischarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VMMCId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("VmmcMhpeExtracts");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcProcedureExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AEDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AESeverity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventsManagement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdverseEventtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnaesthesiaUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CadreAssistanClinician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CadreClinician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CadreDischargedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concentration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PenisElevatedAbdomen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostOperationMedicationGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostProcedureInstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PulseRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RemovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScheduledNextVisit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SurgicalMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheatreRegisterNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeMakingLastSllit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimePlacementDevice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VMMCId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Voided")
                        .HasColumnType("bit");

                    b.Property<string>("Volume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("VmmcProcedureExtracts");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.Cargo", b =>
                {
                    b.HasOne("Dwapi.Vmmc.Core.Domain.Manifest", null)
                        .WithMany("Cargoes")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.Facility", b =>
                {
                    b.HasOne("Dwapi.Vmmc.Core.Domain.MasterFacility", null)
                        .WithMany("Mentions")
                        .HasForeignKey("MasterFacilityId");
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.Manifest", b =>
                {
                    b.HasOne("Dwapi.Vmmc.Core.Domain.Facility", null)
                        .WithMany("Manifests")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.Subscriber", b =>
                {
                    b.HasOne("Dwapi.Vmmc.Core.Domain.Docket", null)
                        .WithMany("Subscribers")
                        .HasForeignKey("DocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcDiscontinuationExtract", b =>
                {
                    b.HasOne("Dwapi.Vmmc.Core.Domain.Facility", null)
                        .WithMany("VmmcDiscontinuationExtracts")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcEnrollmentExtract", b =>
                {
                    b.HasOne("Dwapi.Vmmc.Core.Domain.Facility", null)
                        .WithMany("VmmcEnrollmentExtracts")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcFollowupVisitExtract", b =>
                {
                    b.HasOne("Dwapi.Vmmc.Core.Domain.Facility", null)
                        .WithMany("VmmcFollowupVisitExtracts")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcMhpeExtract", b =>
                {
                    b.HasOne("Dwapi.Vmmc.Core.Domain.Facility", null)
                        .WithMany("VmmcMhpeExtracts")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Vmmc.Core.Domain.VmmcProcedureExtract", b =>
                {
                    b.HasOne("Dwapi.Vmmc.Core.Domain.Facility", null)
                        .WithMany("VmmcProcedureExtracts")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
